# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

debug {
  disable_logs = false
}

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=HDMI-A-1,1280x1024@75.3Hz,auto,auto


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = caja
$clipboard = cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy

source = ~/.config/hypr/configs/*
