#################
### AUTOSTART ###
#################

$cursor_name = "phinger-cursor-dark"
$cursor_size = 16
$launcher = uwsm app --

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = hyprpaper & firefox
# {# replace_quoted(data.cursor.name) #}
# {# replace_number(data.cursor.size) #}
exec-once = $launcher waybar
# exec-once = $launcher nm-applet # autostart
exec-once = $launcher udiskie --tray
exec-once = $launcher hyprctl setcursor $cursor_name $cursor_size
exec-once = $launcher dunst --startup_notification
exec-once = $launcher wl-paste --type text --watch cliphist store # Stores only text data
exec-once = $launcher wl-paste --type image --watch cliphist store # Stores only image data
exec-once = awww-daemon & awww img ~/Pictures/wallpapers/wallpaper.jpg
#exec-once = $launcher syncthingtray qt-widgets-gui --single-instance --wait
