##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule {
  # Ignore maximize requests from all apps. You'll probably like this.
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  # Fix some dragging issues with XWayland
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

# Hyprland-run windowrule
windowrule {
  name = move-hyprland-run

  match:class = hyprland-run

  move = 20 monitor_h-120
  float = yes
}

windowrule {
  name = kitty
  match:class = ^kitty$
  match:title = ^kitty$
}

windowrule {
  name = pavucontrol
  match:class = ^(org.pulseaudio.pavucontrol)
  float = yes
}

windowrule {
  name = terminals-workspace
  match:class = ^(Alacritty|foot)$
  workspace = 1
}

windowrule {
  name = browser-workspace
  match:class = ^(firefox)$
  workspace = 2
}

windowrule {
  name = discord-workspace
  match:class = ^(discord)$
  workspace = 8
}

windowrule {
  name = aottg2
  match:class = ^Aottg2Linux.*$
  match:title = ^Aottg2$
  size = 1280 720
  workspace = 9
  float = yes
  content = game
}

windowrule {
  name = osu
  match:class = ^osu!$
  match:title = ^osu!$
  workspace = 9
  float = yes
  fullscreen = yes
  content = game
}

windowrule {
  name = obsidian
  match:class = ^obsidian$
  workspace = 4
}

windowrule {
  name = logseq
  match:class = ^Logseq$
  workspace = 5
}

windowrule {
  name = visual-studio-code
  match:class = ^Code$
  workspace = 6
}

windowrule {
  name = code
  match:class = ^Code$
  workspace = 10
}

windowrule {
  name = obs
  match:class = ^com.obsproject.Studio$
  workspace = 10
}

windowrule {
  name = syncthingtray
  match:class = ^syncthingtray$
  size = 500 500
  float = yes
  move = (monitor_w-window_w) (monitor_h-window_h)
}
